# -*- conf -*-
[package]

name = "static_templater"
version = "0.0.1"
authors = ["lvo"]
# build = "build.rs"


[lib]
name = "static_templater"
path = "src/lib.rs"
test = true
plugin = true
crate-type = ["dylib"]


[build-dependencies.peg]
git = "https://github.com/kevinmehall/rust-peg"
